application: sbrs-01
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: 1d

- url: /get
  script: main.py
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
    
- url: /shell.*
  script: shell.py
  login: admin
